<<<<<<< Updated upstream
[tools]
node = "24"

[env]
# DOCKER
DOCKER_DIR="_tools/docker"
COMPOSE_FILE="docker-compose-local-bdd.yml"


=======
[tools]
node = "22"

[env]
# DOCKER
DOCKER_DIR="_tools/docker"
COMPOSE_FILE="docker-compose-local-bdd.yml"


>>>>>>> Stashed changes
